version: '3.9'

services:
  frontend:
    container_name: nt_frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    restart: always
    depends_on:
      - backend
  backend:
    container_name: nt_backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres?schema=public
  db:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}