version: '3.9'

services:
  backend:
    container_name: nt_backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres?schema=public
  db:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}